@url=http://localhost:5000/api

### Test Case: Get all books
GET {{url}}/books

### get books by id
GET {{url}}/books/1

### get book by title
GET {{url}}/books/title/The Great Gatsby

### post a new book
POST {{url}}/books
Content-Type: application/json

{
    "title": "skyward",
    "author": "Brandon Sanderson",
    "publication_year": 2018,
    "language": "English",
    "open_library_id": "OL12342678M"
}

### delete a book by id
DELETE {{url}}/books/13


### update a book by id
PUT {{url}}/books/11
Content-Type: application/json

{
    "title": "The Lord of the Flies",
    "author": "William Goolding",
    "publication_year": 1954,
    "language": "English",
    "open_library_id": "OL12345678M"
}